id: P010499
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG16599
  title: གངས་ཅན་རིག་བརྒྱའི་སྒོ་འབྱེད་ལྡེ་མིག ༼དེབ་དང་པོ།༽
  author: ''
  volumes:
    f29f374c127d4361ba59d3fdaa85ed47:
      image_group_id: I1KG16617
      title: ''
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
